// ------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY SEMANTIC-RELEASE.
// DO NOT EDIT MANUALLY.
// ------------------------------------------------------------

export interface VersionInfo {
  version: string;
  releaseDate: string;
}

export const versionInfo: VersionInfo = {
  version: '2.24.2',
  releaseDate: '2026-08-11T12:15:27Z',
};
