// ------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY SEMANTIC-RELEASE.
// DO NOT EDIT MANUALLY.
// ------------------------------------------------------------

export interface VersionInfo {
  version: string;
  releaseDate: string;
}

export const versionInfo: VersionInfo = {
  version: '2.21.0',
  releaseDate: '2026-01-20T18:17:17Z',
};
